apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "testapp1"
  annotations:
    github.com/project-slug: dexmach-backstage-demo/testapp1
    backstage.io/kubernetes-id: "testapp1"
    backstage.io/kubernetes-namespace: "testapp1"
    backstage.io/kubernetes-cluster: aks-pe-poc-01
    backstage.io/techdocs-ref: dir:.
    azure.com/tag-selector: backstage-entity-id/testapp1
  links:
    - url: https://testapp1.jandelaet.com
      title: Website
spec:
  type: service
  owner: group:cloud-native
  lifecycle: experimental
  dependsOn:
    - Resource:acrdmbackstagepoc
    - Resource:aks-pe-poc-01
    - Resource:jandelaet.com
